ontology:
  model_name: "gemini-1.5-flash-001"
  max_output_tokens: 8192
  max_input_characters: 500000
  temperature: 1.5
  top_p: 0.1
  min_urls_count: 5
  output_file: output/ontology.json
  cache_file: cache/scrape_cache.json
  max_workers: 16

extract_data:
  model_name: "gemini-1.5-flash-001"
  max_output_tokens: 8192
  max_input_characters: 500000
  temperature: 1.5
  top_p: 0.1
  ontology_file: output/ontology.json
  cache_file: cache/scrape_cache.json
  max_workers: 16

query_graph:
  ontology_file: output/ontology.json
  cypher:
    model_name: "gemini-1.5-flash-001"
    max_output_tokens: 8192
    max_input_characters: 500000
    temperature: 1.5
    top_p: 0.1
  qa:
    model_name: "gemini-1.5-flash-001"
    max_output_tokens: 8192
    max_input_characters: 500000
    temperature: 1.5
    top_p: 0.1
